SRC_DIR=/projects/amdis/e3sm-amdis/components/homme
NC_PATH=$NETCDF_ROOT
NF_PATH=/projects/amdis/tpl
VENV_ROOT=$SCRATCH/amdis-env

BUILD_DIR=$SCRATCH/build-e3sm-amdis

cmake -B $BUILD_DIR \
-DCMAKE_BUILD_TYPE=DEBUG \
-DCMAKE_CXX_COMPILER=mpicxx \
-DCMAKE_C_COMPILER=mpicc \
-DCMAKE_Fortran_COMPILER=mpifort \
-DCMAKE_C_FLAGS="-fPIC" \
-DCMAKE_CXX_FLAGS="-fPIC" \
-DCMAKE_Fortran_FLAGS="-fPIC" \
-DCMAKE_CXX_STANDARD=17 \
-DHOMME_FIND_BLASLAPACK=ON \
-DHOMMEXX_BFB_TESTING=OFF \
-DHOMME_AMDIS_PROJECT:BOOL=ON \
-DHOMME_BUILD_PYHOMMEXX=ON \
-DHOMMEXX_ENABLE_FAD_TYPES:BOOL=ON \
-DTrilinos_ROOT=${NF_PATH} \
-DPYHOMMEXX_NLEV:STRING=128 \
-DPYHOMMEXX_QSIZE:STRING=10 \
-DNetCDF_C_PATH=$NC_PATH \
-DNetCDF_Fortran_PATH=${NF_PATH} \
-DKokkos_ENABLE_CUDA=OFF \
-DKokkos_ENABLE_SERIAL=ON \
-DKokkos_ENABLE_OPENMP=ON \
-DKokkos_ARCH_NATIVE=ON \
-DPython_ROOT_DIR=$VENV_ROOT \
-DPython_INCLUDE_DIRS=$VENV_ROOT/include \
-DPython_LIBRARIES=$VENV_ROOT/lib \
-S $SRC_DIR
